### PR TITLE
Update layer to 133

### PR DESCRIPTION
**Pull request by pogudin-sergey**
Fix UDPATE_APP_TO_LOGIN & up layer to133

### CODE REVIEW

**Comment by freeman69rus** [comment]
I am getting this error

> if (message.result._ === 'mt_rpc_error') {
> 
> TypeError: Cannot read property '_' of undefined

in `rpc\index.js:549`

**Comment by pogudin-sergey** [comment]
> I am getting this error
> 
> > if (message.result._ === 'mt_rpc_error') {
> > TypeError: Cannot read property '_' of undefined
> 
> in `rpc\index.js:549`

How repeat this case?

**Comment by alik0211** [comment]
Thanks! ❤️

**Comment by pogudin-sergey** [comment]
> Thanks! ❤️

Please, up version for npm

**Comment by alik0211** [comment]
@pogudin-sergey done

**Comment by pogudin-sergey** [comment]
> @pogudin-sergey done

Thank you!

**Comment by freeman69rus** [comment]
> > I am getting this error
> > > if (message.result._ === 'mt_rpc_error') {
> > > TypeError: Cannot read property '_' of undefined
> > 
> > 
> > in `rpc\index.js:549`
> 
> How repeat this case?

call auth.signIn method

**Comment by pogudin-sergey** [comment]
> call `auth.signIn` method

Look params in you call method. Params do not have "_" key. This is not layer problem.

**Comment by freeman69rus** [comment]
> Look params in you call method. Params do not have "_" key. This is not layer problem.
Everything worked fine before updating the layer.

I send these params:
> phone_code
> phone_number
> phone_code_hash

**Comment by pogudin-sergey** [comment]
> Don't you have a similar problem?
No problem for 170 users.

Worked code:
```js 
sendCode(phone) {
    return this.mtproto.call(
      'auth.sendCode',
      {
        phone_number: phone,
        api_id: config.telegram.appId,
        api_hash: config.telegram.hash,
        settings: {
          _: 'codeSettings',
          current_number: false,
          allow_app_hash: false,
        },
      },
      {},
      true,
    );
}
```

I guess you miss codeSettings. Please post full code.

**Comment by freeman69rus** [comment]
> I guess you miss codeSettings. Please post full code.

I have no problem with `auth.sendCode` method.

```js
//sendCode
this.api.call('auth.sendCode', {
                phone_number: this.phone,
                settings: {
                    _: 'codeSettings',
                    current_number: false,
                    allow_app_hash: false
                },
            })

//signIn
this.api.call('auth.signIn', {
                phone_code: code,
                phone_number: this.phone,
                phone_code_hash: codeHash,
            }, { syncAuth: true })
```

**Comment by pogudin-sergey** [comment]
I guess you do not rebuild new tl shemas.
Run scripts in ./node_modules/@mtproto/core directory: 
# npm run generate-builder
# npm run generate-parser

**Comment by freeman69rus** [comment]
> I guess you do not rebuild new tl shemas. 

Thanks!!!!!!!!!!!
But I just installed new version via npm and I didn't have a scripts folder.

**Comment by pogudin-sergey** [comment]
> But I just installed new version via npm and I didn't have a scripts folder.

Fix https://github.com/alik0211/mtproto-core/pull/221

Please like )))

**Pull request merged**
